CREATE TABLE laboratory (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             code VARCHAR(255) NOT NULL,
                             name VARCHAR(255) NOT NULL
);

CREATE TABLE property (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             name VARCHAR(255) NOT NULL
);

CREATE TABLE person (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        initial_date DATE NOT NULL,
                        end_date DATE,
                        description VARCHAR(500),
                        laboratory_id BIGINT,
                        CONSTRAINT fk_person_laboratory FOREIGN KEY (laboratory_id) REFERENCES laboratory (id)
);

ALTER TABLE laboratory
    ADD COLUMN property_id BIGINT,
ADD CONSTRAINT fk_laboratory_property FOREIGN KEY (property_id) REFERENCES property (id);